logging:
  level:
    root: INFO

spring:
  application:
    name: social-multiplication-client
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, loggers, metrics

multiplication:
  solved:
    key: multiplication.solved
  exchange: multiplication_exchange